image:
  - Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
install:
  - git submodule update --init --recursive
build:
  project: OBJCXX.sln
before_build:
  - nuget restore
