language: objective-c
osx_image: xcode8.3
cache:
    directories:
    - $HOME/.ccache
install:
- gem install xcpretty
- brew install ccache
- PATH=$PATH:/usr/local/opt/ccache/libexec
script:
- set -o pipefail && xcodebuild -project "OBJCXX.xcodeproj" -scheme "OBJCXX" build analyze | xcpretty
- set -o pipefail && xcodebuild -project "OBJCXX.xcodeproj" -scheme "OBJCXX-iOS" -destination generic/platform=iOS build analyze | xcpretty
- set -o pipefail && xcodebuild -project "OBJCXX.xcodeproj" -scheme "OBJCXX-Test" build analyze | xcpretty
before_script:
- ccache -s
- ccache -z
after_script:
- ccache -s
after_success:
- bash Scripts/travis-after.sh
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
